language: scala

env:
  matrix:
    - SCRIPT="bin/runSbtJob consumer-service/consumer-service-java-sbt test"
    - SCRIPT="bin/runSbtJob consumer-service/consumer-service-java-sbt test"
    - SCRIPT="bin/runSbtJob cors/cors-java test"
    - SCRIPT="bin/runSbtJob cors/cors-scala test"
    - SCRIPT="bin/runSbtJob file-download/file-download-scala-sbt test"
    - SCRIPT="bin/runSbtJob file-upload/file-upload-scala-sbt test"
    - SCRIPT="bin/runSbtJob file-upload/file-upload-java-sbt test"
    - SCRIPT="bin/runSbtJob http-header-handling/http-header-handling-java-sbt test"
    - SCRIPT="bin/runSbtJob mixed-persistence/mixed-persistence-java-sbt test"
    - SCRIPT="bin/runSbtJob mixed-persistence/mixed-persistence-scala-sbt test"
    - SCRIPT="mvn -f circuitbreakerpanel/circuitbreakerpanel-java-mvn test"
    - SCRIPT="mvn -f i18n/hello-i18n-java-mvn test"
    - SCRIPT="mvn -f kubernetes-deployment/hello-kubernetes-java-mvn test"
    # can't run telemetry recipes on travis
    #- SCRIPT="mvn -f lightbend-telemetry/lightbend-telemetry-java-mvn test"
    #- SCRIPT="mvn -f lightbend-telemetry/log-correlation-java-mvn test"

before_install:
  # See https://github.com/travis-ci/travis-ci/issues/4629#issuecomment-239493916
  - rm ~/.m2/settings.xml
  - curl -Ls https://git.io/jabba | bash && . ~/.jabba/jabba.sh

install: jabba install adopt@1.8.192-12 && jabba use $_ && java -version
script: $SCRIPT

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.jabba/jdk
    - $HOME/.m2/repository
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2aa0aeda88d31fe293d4
    on_success: change
    on_failure: always
    on_start: never
